<a href="https://colab.research.google.com/github/desouki76/Ahmed/blob/main/NLP_Preprocssing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [2]:
# Download NLTK resources if not available
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [3]:
 #Sample corpus
corpus = [
    "Thor ate pizza",
    "Loki is tall",
    "Loki is eating pizza"
]

In [4]:

# Initialize tools
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

In [5]:
# Initialize tools
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

In [6]:
# Preprocessing function
def preprocess(text):
    tokens = nltk.word_tokenize(text.lower())  # tokenize + lowercase
    tokens = [t for t in tokens if t.isalpha()]  # keep only words
    tokens = [t for t in tokens if t not in stop_words]  # remove stopwords
    tokens = [lemmatizer.lemmatize(t) for t in tokens]  # lemmatization
    return " ".join(tokens)

In [7]:

# Apply preprocessing
clean_corpus = [preprocess(doc) for doc in corpus]

print("Cleaned Corpus:", clean_corpus)

Cleaned Corpus: ['thor ate pizza', 'loki tall', 'loki eating pizza']


In [8]:

# Apply N-grams (1 to 3 → unigram, bigram, trigram)
vectorizer = CountVectorizer(ngram_range=(1,3))
X = vectorizer.fit_transform(clean_corpus)

print("\nVocabulary:", vectorizer.get_feature_names_out())
print("\nMatrix:\n", X.toarray())


Vocabulary: ['ate' 'ate pizza' 'eating' 'eating pizza' 'loki' 'loki eating'
 'loki eating pizza' 'loki tall' 'pizza' 'tall' 'thor' 'thor ate'
 'thor ate pizza']

Matrix:
 [[1 1 0 0 0 0 0 0 1 0 1 1 1]
 [0 0 0 0 1 0 0 1 0 1 0 0 0]
 [0 0 1 1 1 1 1 0 1 0 0 0 0]]


In [9]:
# .  >>> Distance
# code[^Ali] >> search "Code Ali" but استعرض exclude Ali
# * >> to the rest
# Code(Ali) >> searh "Code Ali"
# \n New Line
# \w >> [0 - 9] [A - Z] [a - z]
#\W >>> any thing excluding [0 - 9] [a- z] [A -Z]
#\s >>> White space
#\S >>> not white space


In [18]:
text = '''
Tesla's gross cost of operating lease vehicles in FY2021 Q1 was $4.85 billion.
In previous quarter i.e. FY2020 Q4 it was $3 billion.
'''

In [11]:
import re


In [19]:
# FY2021 Q1,   $4.85 , FY2020 Q4

patern = r'FY\d{4}.Q[1-4][^\$]+\$[0-9.]+'
re.findall(patern, text)


['FY2021 Q1 was $4.85', 'FY2020 Q4 it was\xa0$3']

In [40]:
# replace the new slaery with 6000000
text = r' I m Ali my old salery is 1000000 L.E and my new salery is 2000000 L.E'
patern = 'new.salery.is.([0-9]+)'
re.sub(patern,'new salery 6000000', text )

' I m Ali my old salery is 1000000 L.E and my new salery 6000000 L.E'

In [43]:
# replace the new slaery with 6000000
text = r' I m Ali my old salery is 1000000 L.E and my new salery is 2000000 L.E'
patern = '[^\n]+([0-9]+)'
re.sub(patern,' 6000000', text )

' 6000000 L.E'

In [46]:
import re
import nltk
from nltk import sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import CountVectorizer


In [47]:
nltk.download('punkt')
nltk.download('punkt_tap')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Error loading punkt_tap: Package 'punkt_tap' not found in
[nltk_data]     index
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [45]:
corpus = [
    "Thor ate pizza",
    "Loki is tall",
    "Loki is eating pizza"
]

In [ ]:
#Intlize tools
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))


In [48]:
def preprocess (text):
  token = nltk.word_tokenize(text.lower()) #word toknie and lower case
  filterd = [lemmatizer.lemmatize(w) for w in token if w not in stop_words and w.isalpha ]
  return ''.join(filterd)


In [50]:
#clean corpus
clean_corpus = [preprocess(doc) for doc in corpus]
print ('Cleand Paraphrah Corpuss:', clean_corpus)


Cleand Paraphrah Corpuss: ['thoratepizza', 'lokitall', 'lokieatingpizza']


In [51]:
#Apply N Gram 1:1 as BoW
vectorizer = CountVectorizer(ngram_range=(1,1)) #Uni Gram
x= vectorizer.fit_transform(clean_corpus)


print('\nVocabulary:', vectorizer.get_feature_names_out())
print('\nMatrix:\n', x.toarray())




Vocabulary: ['lokieatingpizza' 'lokitall' 'thoratepizza']

Matrix:
 [[0 0 1]
 [0 1 0]
 [1 0 0]]


In [52]:
#Apply N Gram 1:2
vectorizer = CountVectorizer(ngram_range=(1,2)) #Bi Gram
x= vectorizer.fit_transform(clean_corpus)


print('\nVocabulary:', vectorizer.get_feature_names_out())
print('\nMatrix:\n', x.toarray())


Vocabulary: ['lokieatingpizza' 'lokitall' 'thoratepizza']

Matrix:
 [[0 0 1]
 [0 1 0]
 [1 0 0]]


In [53]:
#Apply N Gram 1:3
vectorizer = CountVectorizer(ngram_range=(1,3)) #Tri Gram
x= vectorizer.fit_transform(clean_corpus)


print('\nVocabulary:', vectorizer.get_feature_names_out())
print('\nMatrix:\n', x.toarray())


Vocabulary: ['lokieatingpizza' 'lokitall' 'thoratepizza']

Matrix:
 [[0 0 1]
 [0 1 0]
 [1 0 0]]
